my_data<-read.csv('out.csv')
library(car)
summary(aov(TotalTime ~ KeyboardType * InputType, data = my_data))
summary(aov(TotalTime ~ KeyboardType * Movement, data = my_data))
summary(aov(Accuracy ~ KeyboardType * InputType, data = my_data))
summary(aov(Accuracy ~ KeyboardType * Movement, data = my_data))

sprintf("totaltime")
mean(subset(my_data, KeyboardType == 'normal')$TotalTime)
mean(subset(my_data, KeyboardType == 'zoom')$TotalTime)
mean(subset(my_data, InputType == 'alpha')$TotalTime)
mean(subset(my_data, InputType == 'symbol')$TotalTime)
mean(subset(my_data, Movement == 'still')$TotalTime)
mean(subset(my_data, Movement == 'moving')$TotalTime)
mean(my_data$TotalTime)
sprintf("accuracy")
mean(subset(my_data, KeyboardType == 'normal')$Accuracy)
mean(subset(my_data, KeyboardType == 'zoom')$Accuracy)
mean(subset(my_data, InputType == 'alpha')$Accuracy)
mean(subset(my_data, InputType == 'symbol')$Accuracy)
mean(subset(my_data, Movement == 'still')$Accuracy)
mean(subset(my_data, Movement == 'moving')$Accuracy)
mean(my_data$Accuracy)

library(easyGgplot2)
ggplot2.histogram(data=subset(my_data, select=c("KeyboardType", "TotalTime")), xName='TotalTime',groupName='KeyboardType', legendPosition="top",alpha=0.5)
ggplot2.histogram(data=subset(my_data, select=c("InputType", "TotalTime")), xName='TotalTime',groupName='InputType', legendPosition="top",alpha=0.5)
ggplot2.histogram(data=subset(my_data, select=c("Movement", "TotalTime")), xName='TotalTime',groupName='Movement', legendPosition="top",alpha=0.5)
ggplot2.histogram(data=subset(my_data, select=c("KeyboardType", "Accuracy")), xName='Accuracy',groupName='KeyboardType', legendPosition="top",alpha=0.5)
ggplot2.histogram(data=subset(my_data, select=c("InputType", "Accuracy")), xName='Accuracy',groupName='InputType', legendPosition="top",alpha=0.5)
ggplot2.histogram(data=subset(my_data, select=c("Movement", "Accuracy")), xName='Accuracy',groupName='Movement', legendPosition="top",alpha=0.5)
